# Generated by Django 4.1.5 on 2023-01-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
