# Generated by Django 4.1.5 on 2023-01-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('created_at', models.CharField(max_length=100, unique=True)),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.CharField(max_length=100, unique=True)),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('created_at', models.CharField(max_length=100, unique=True)),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('created_at', models.CharField(max_length=100, unique=True)),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
            ],
        ),
    ]
