# Generated by Django 4.1.5 on 2023-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
                ('created_epoch', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
