# Generated by Django 4.1.5 on 2023-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_humidity_light_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='expiration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='led',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='led',
            name='expiration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='expiration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='expiration',
            field=models.CharField(max_length=100),
        ),
    ]
