# Generated by Django 4.1.5 on 2023-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pump',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
